name: Go CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true

      # -------------------------
      # Vulnerability Scan
      # -------------------------
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: "1.22.x"
          go-package: ./...

      # -------------------------
      # Linting
      # -------------------------
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.1.2
          args: run ./...

      # -------------------------
      # Tests
      # -------------------------
      - name: Run tests
        run: go test ./...

      # -------------------------
      # Build (ONLY if above pass)
      # -------------------------
      - name: Build binary
        run: go build -o ./bin/api ./cmd/server
